#!/bin/bash  

#
# Здесь можно менять параметры (пробелы вокруг знака равно будут ошибкой)
#
 
# аккаунт учителя. нужен чтобы исключить из бэкапа
# тк cron, автоматическое определение лучше не использовать
TEACHER_NAME="teacher" 

# директория, где будет храниться бэкап
BACKUPS_DIR="/home/$TEACHER_NAME/backups"

# Дальше править не нужно, если вы не понимаете, что делаете


DATE_PREF=`date +%F`



# создаем директорию для бэкапа, если еще не
if ! [ -d $BACKUPS_DIR ]; then
mkdir $BACKUPS_DIR
fi


# создаем дампы баз данных MySQL. Обязательно указываем пользователя и пароль
mysqldump -q -u root -p1234 -h localhost -A  > $BACKUPS_DIR/$DATE_PREF.sql
 

# создаем tar'ом
tar cpf $BACKUPS_DIR/$DATE_PREF.tar --exclude='home/'$TEACHER_NAME /home/ 
#>/dev/null 2>&1


tar -czf $BACKUPS_DIR/$DATE_PREF.tgz -C $BACKUPS_DIR $DATE_PREF.tar $DATE_PREF.sql

cd $BACKUPS_DIR

rm -f $DATE_PREF.sql $DATE_PREF.tar


# ищем файлы старше 14 суток и удаляем их, дабы не засорять жесткий диск
find ./backups/ -mtime +14 -print -mindepth 1 -delete >/dev/null 2>&1

